steps:
  # Run tests and save to file
  - name: golang:1.18
    entrypoint: /bin/bash

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag', 
           'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/myimage', '-f', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/myimage']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'helloworld-${SHORT_SHA}', 
           '--image=us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/myimage', 
           '--region', 'us-central1', '--platform', 'managed']
