steps:
  # Run tests and save to file
  - name: golang:1.18
    #entrypoint: /bin/bash

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/end-to-end-demo-v1/myimage', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/end-to-end-demo-v1/myimage']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'gcr.io/$PROJECT_ID/end-to-end-demo-v1/myimage', 
           '--image=nate/myimage', 
           '--region', 'us-central1', '--platform', 'managed']
